ARG BASE_RUNNER=quay.io/rhoai-devops/base-runner:latest
FROM $BASE_RUNNER AS git-clone

ARG SECRET_NAME=devops-infra-ssh-key-devops-image-builds
WORKDIR /app
USER root
ENV GIT_SSH_COMMAND="ssh -i /run/secrets/${SECRET_NAME}/ssh-privatekey -o UserKnownHostsFile=/run/secrets/${SECRET_NAME}/known_hosts"
RUN --mount=type=secret,id=${SECRET_NAME} \
    git clone git@github.com:red-hat-data-services/rhods-devops-infra.git

FROM $BASE_RUNNER
WORKDIR /app
COPY --from=git-clone /app/rhods-devops-infra/tools/tracer/tracer.sh /app/tracer.sh
