apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/devops-runner-images?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" 
      && target_branch == "main" && 
      ( "./openshift-utils/***".pathChanged() 
        || ".tekton/devops-openshift-utils-push.yaml".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: devops-runner-images
    appstudio.openshift.io/component: devops-openshift-utils
    pipelines.appstudio.openshift.io/type: build
  name: devops-openshift-utils-on-push
  namespace: rhoai-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/rhoai-devops/openshift-utils:{{revision}}
  - name: additional-tags
    value:
      - latest
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: openshift-utils
  - name: build-args-file
    value: ./argfile.conf
  - name: skip-checks
    value: true
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/red-hat-data-services/devops-runner-images.git"
      - name: revision
        value: '{{revision}}'
      - name: pathInRepo
        value: ".tekton/pipelines/multi-arch-container-build.yaml" 
  taskRunTemplate:
    serviceAccountName: build-pipeline-devops-openshift-utils
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
